repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
    - id: lint-rules
      name: lint-rules
      entry: python3 scripts/lint_rules.py
      language: system
      pass_filenames: false
